# Generated by Django 3.2.6 on 2021-08-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resume/image/')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cv_file', models.FileField(upload_to='resume/files/')),
            ],
        ),
    ]
