# Generated by Django 3.2.6 on 2021-08-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
