# Generated by Django 3.2.6 on 2021-08-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210828_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to='portfolio/porjects/'),
            preserve_default=False,
        ),
    ]
